Added support for create group and add user
namaggarwal/splitwise pull request #11
Opened 2017-06-16 03:04 UTC by samta

2017-06-19 07:20 UTC, namaggarwal requested changes
Please have a look at the comments. I guess while creating a resource we should take resource object as input. This will help us to maintain the code and prevent breaking changes when splitwise adds more field in their APIs

2017-06-19 07:20 UTC, namaggarwal commented on splitwise/__init__.py
> +    def addUserToGroup(self, first_name=None, last_name=None, email=None, id=0):
It should take a user object as input. See createExpense.

id should be group_id for clarity

2017-06-19 07:20 UTC, namaggarwal commented on splitwise/__init__.py
> +    def createGroup(self, name=None, group_type=None, country_code=None):
It should take group object as input, see createExpense

2017-06-20 08:09 UTC, samta commented
Thanks for reviewing. I will do the suggested changes and raise a review request again.

One doubt, the create group api page (http://dev.splitwise.com/dokuwiki/doku.php?id=create_group) suggests that we can add members also when try to create group, but when I am posting this api request its not adding members. But the group has got created successfully.

{'members': [{'first_name': '<Name>, 'last_name': '<Title>', 'email': '<email-address>'}], 'country_code': 123, 'name': 'test-group2', 'group_type': 'test-type'}

Can you please suggest ?

2017-06-21 12:54 UTC, namaggarwal commented
I will have a look at that

2017-06-21 16:06 UTC, samta commented
Thanks for replying back Naman,

Looks like members is not a valid key, below has worked.
{'users_1_first_name': ', 'users_1_last_name': '', 'users_1_email': '', 'country_code': 123, 'name': 'test-group2', 'group_type': 'test-type'}

2017-06-23 13:55 UTC, samta commented
Hi Naman,

Please review.

Here I have taken care of creating group object and let the create group method to take care of calling the api. I have also made a common method to create users as in required format users__0__ ..

I have modified two other files in order to init the object.

If you find the changes fine, I will also checkin example to create group.

2017-06-30 09:07 UTC, namaggarwal requested changes
Hi,

The functionality is fine but the object returned should be a group object. I added some minor comments as well.

Naman

2017-06-30 09:07 UTC, namaggarwal commented on splitwise/__init__.py
> +    CREATE_GROUP_URL = SPLITWISE_BASE_URL + "api/" + SPLITWISE_VERSION + "/create_group"
Please align this like other URLs

2017-06-30 09:07 UTC, namaggarwal commented on splitwise/__init__.py
>          return content
Please return a Group object like in createExpense

2017-06-30 09:07 UTC, namaggarwal commented on splitwise/user.py
> +            self.picture    = Picture(data["picture"])
You can add a condition here if 'picture' in data:

2017-07-01 14:59 UTC, merged